local _M = {}

_M.DECISION_ALLOW = "ALLOW"
_M.DECISION_VIOLATION = "VIOLATION"

_M.REASON_INVARIANT_OK = "INVARIANT_OK"
_M.REASON_INVARIANT_VIOLATION = "INVARIANT_VIOLATION"
_M.REASON_MISSING_EXPECTED = "MISSING_EXPECTED"
_M.REASON_MISSING_ACTUAL = "MISSING_ACTUAL"
_M.REASON_PARSE_ERROR_EXPECTED = "PARSE_ERROR_EXPECTED"
_M.REASON_PARSE_ERROR_ACTUAL = "PARSE_ERROR_ACTUAL"

return _M
